development:
    spectrify_client_id: <%= ENV["spectrify_client_id"] %>
    spetrify_client_secret: <%= ENV["spectrify_client_secret"] %>
test:
    spectrify_client_id: <%= ENV["spectrify_client_id"] %>
    spetrify_client_secret: <%= ENV["spectrify_client_secret"] %>
production:
    spectrify_client_id: <%= ENV["spectrify_client_id"] %>
    spetrify_client_secret: <%= ENV["spectrify_client_secret"] %>