development:
    SPECTRIFY_CLIENT_ID: <%= ENV["SPECTRIFY_CLIENT_ID"] %>
    SPECTRIFY_CLIENT_SECRET: <%= ENV["SPECTRIFY_CLIENT_SECRET"] %>
    SPECTRIFY_REDIRECT_URI: <%= ENV["SPECTRIFY_REDIRECT_URI"] %>
test:
    SPECTRIFY_CLIENT_ID: <%= ENV["SPECTRIFY_CLIENT_ID"] %>
    SPECTRIFY_CLIENT_SECRET: <%= ENV["SPECTRIFY_CLIENT_SECRET"] %>
    SPECTRIFY_REDIRECT_URI: <%= ENV["SPECTRIFY_REDIRECT_URI"] %>
production:
    SPECTRIFY_CLIENT_ID: <%= ENV["SPECTRIFY_CLIENT_ID"] %>
    SPECTRIFY_CLIENT_SECRET: <%= ENV["SPECTRIFY_CLIENT_SECRET"] %>
    SPECTRIFY_REDIRECT_URI: <%= ENV["SPECTRIFY_REDIRECT_URI"] %>