{
	"timestamp": 1559651017556,
	"context": {
		"external_urls": {
			"spotify": "https://open.spotify.com/artist/5T4UKHhr4HGIC0VzdZQtAE"
		},
		"href": "https://api.spotify.com/v1/artists/5T4UKHhr4HGIC0VzdZQtAE",
		"type": "artist",
		"uri": "spotify:artist:5T4UKHhr4HGIC0VzdZQtAE"
	},
	"progress_ms": 56995,
	"item": {
		"album": {
			"album_type": "album",
			"artists": [ {
				"external_urls": {
					"spotify": "https://open.spotify.com/artist/5T4UKHhr4HGIC0VzdZQtAE"
				},
				"href": "https://api.spotify.com/v1/artists/5T4UKHhr4HGIC0VzdZQtAE",
				"id": "5T4UKHhr4HGIC0VzdZQtAE",
				"name": "Faithless",
				"type": "artist",
				"uri": "spotify:artist:5T4UKHhr4HGIC0VzdZQtAE"
			} ],
			"available_markets": [
				"AD",
				"AE",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BH",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JO",
				"JP",
				"KW",
				"LB",
				"LI",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PH",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"SA",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TN",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"external_urls": {
				"spotify": "https://open.spotify.com/album/1aNeaOGtdGEPYH2TBqv7nA"
			},
			"href": "https://api.spotify.com/v1/albums/1aNeaOGtdGEPYH2TBqv7nA",
			"id": "1aNeaOGtdGEPYH2TBqv7nA",
			"images": [ {
					"height": 640,
					"url": "https://i.scdn.co/image/595b4b589675e1ee5ce4d450c515a61a5185cabf",
					"width": 640
				},
				{
					"height": 300,
					"url": "https://i.scdn.co/image/e449796813532e71016fc56a73dd824c39db391e",
					"width": 300
				},
				{
					"height": 64,
					"url": "https://i.scdn.co/image/ef15ff94fc870400d3bd6336a2fc3a166442f418",
					"width": 64
				}
			],
			"name": "Live At Alexandra Palace",
			"release_date": "2005",
			"release_date_precision": "year",
			"total_tracks": 18,
			"type": "album",
			"uri": "spotify:album:1aNeaOGtdGEPYH2TBqv7nA"
		},
		"artists": [ {
			"external_urls": {
				"spotify": "https://open.spotify.com/artist/5T4UKHhr4HGIC0VzdZQtAE"
			},
			"href": "https://api.spotify.com/v1/artists/5T4UKHhr4HGIC0VzdZQtAE",
			"id": "5T4UKHhr4HGIC0VzdZQtAE",
			"name": "Faithless",
			"type": "artist",
			"uri": "spotify:artist:5T4UKHhr4HGIC0VzdZQtAE"
		} ],
		"available_markets": [
			"AD",
			"AE",
			"AR",
			"AT",
			"AU",
			"BE",
			"BG",
			"BH",
			"BO",
			"BR",
			"CA",
			"CH",
			"CL",
			"CO",
			"CR",
			"CY",
			"CZ",
			"DE",
			"DK",
			"DO",
			"DZ",
			"EC",
			"EE",
			"EG",
			"ES",
			"FI",
			"FR",
			"GB",
			"GR",
			"GT",
			"HK",
			"HN",
			"HU",
			"ID",
			"IE",
			"IL",
			"IN",
			"IS",
			"IT",
			"JO",
			"JP",
			"KW",
			"LB",
			"LI",
			"LT",
			"LU",
			"LV",
			"MA",
			"MC",
			"MT",
			"MX",
			"MY",
			"NI",
			"NL",
			"NO",
			"NZ",
			"OM",
			"PA",
			"PE",
			"PH",
			"PL",
			"PS",
			"PT",
			"PY",
			"QA",
			"RO",
			"SA",
			"SE",
			"SG",
			"SK",
			"SV",
			"TH",
			"TN",
			"TR",
			"TW",
			"US",
			"UY",
			"VN",
			"ZA"
		],
		"disc_number": 1,
		"duration_ms": 287440,
		"explicit": false,
		"external_ids": {
			"isrc": "GBBXH0500112"
		},
		"external_urls": {
			"spotify": "https://open.spotify.com/track/0fieOH15kx21A7CzfuZw7g"
		},
		"href": "https://api.spotify.com/v1/tracks/0fieOH15kx21A7CzfuZw7g",
		"id": "0fieOH15kx21A7CzfuZw7g",
		"is_local": false,
		"name": "Miss U Less, See U More - Live At Alexandra Palace",
		"popularity": 19,
		"preview_url": "https://p.scdn.co/mp3-preview/c271697b45b02a41d86f64b6723c2068490c90c3?cid=b1a2f527a83b47cfb49a8532c5dfd3ef",
		"track_number": 9,
		"type": "track",
		"uri": "spotify:track:0fieOH15kx21A7CzfuZw7g"
	},
	"currently_playing_type": "track",
	"actions": {
		"disallows": {
			"resuming": true
		}
	},
	"is_playing": true
}